### PR TITLE
Change timbre configuration to log to standard out by default

### PR DESCRIPTION
**Pull request by sbennett33**
I enabled the :standard-out appender in the timbre configuration

### CODE REVIEW

**Comment by lbradstreet** [comment]
Hi @sbennett33, thanks for the PR!

Will this cause info messages to be written to stdout? By default we'd like it if only errors are written to stdout, and info, warn, and errors are written to the log appender.

Cheers

Lucas

**Comment by sbennett33** [comment]
Got it. Let me see what I can do.

**Comment by MichaelDrogalis** [comment]
Thanks @sbennett33. I'll put this out with the next `0.6.0` release. I've added you to the contributors list on the `README` and added you as a collaborator if you'd like to continue helping. Appreciated!

**Comment by sbennett33** [comment]
Awesome! Thanks and glad to help. 

I'm just getting started with clojure and functional programming in general so I'll only be able to pick around the edges and help out with small issues for a while until I get my bearings. 

I've recently become a "stay-at-home-dad" following the collapse of my startup and I'm taking the time to do some research and contribute to some open source projects. I'm working my way through "Out of the Tar Pit" right now and could use any recommendations you might have on papers I should check out next.

Cheers!

**Comment by MichaelDrogalis** [comment]
Great to hear @sbennett33! I really enjoyed watching all of Rich Hickey's talks on InfoQ - might be a good starting point.

If you're interested, we have a fun chat room in Gitter dedicated to this project: https://gitter.im/MichaelDrogalis/onyx

**Pull request merged**
